### ISSUE TITLE
CONTRIBUTORS.md is incorrect

### ISSUE THREAD

**Issue by sparky8251** [vesotv/veso-web#4]
Currently you have all Jellyfin contributors listed as Veso contributors but haven't changed the Emby contributor list.

Please put back the Jellyfin header for the contributors file.

Additionally if you want to, you can rename the file to JELLYFIN-CONTRIBUTORS.md and make a new CONTRIUTORS.md of just Veso contributors.

Thanks for your understanding :)

**Comment by dannymichel** [comment]
https://github.com/vesotv/veso-web/commit/d5c5d38dacdbf9cb0390c528686f2f9d547f45db
